#!/bin/bash

# LICENSE ######################################################################
#
# Copyright 2025 Danny Wahl (danny@instructure.com)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# PARSE OPTS ###################################################################
getopts "h" OPT
if [ "$OPT" == "h" ]; then
  echo "Usage: $0 <password> <salt>"
  exit 0
fi
if [ $# -lt 2 ]; then
  echo 1>&2 "Not enough arguments"
  echo "$0 -h for help"
  exit 1
fi
if [ $# -gt 2 ]; then
  echo 1>&2 "Too many arguments"
  echo "$0 -h for help"
  exit 1
fi

# GENERATE SSHA ################################################################
echo -n "$(echo -n $1$2 | shasum -a 1 | awk '{print $1}')$2" | base64 -w 0 | awk '{print "{SSHA}" $0}'
exit 0